name: CI

on: [pull_request, push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install custom tap
      run: |
        mkdir -p /usr/local/Homebrew/Library/Taps/$GITHUB_REPOSITORY
        cp -r * /usr/local/Homebrew/Library/Taps/$GITHUB_REPOSITORY/
    - name: Check tap installed
      run: brew tap
